import { readFileSync } from 'node:fs'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { renderSkillsIndex, writeSkillsIndex } from '@main/skills/indexFile'
import { SkillRegistry } from '@main/skills/registry'
import type { SkillMeta } from '@shared/types'
import { createHarness, skillDoc, type Harness } from './helpers'

let h: Harness
let registry: SkillRegistry

beforeEach(() => {
  h = createHarness()
  registry = new SkillRegistry({ db: h.db, config: h.config })
})

afterEach(() => {
  h.db.close()
  h.cleanup()
})

function stubSkill(overrides: Partial<SkillMeta>): SkillMeta {
  return {
    id: 'x',
    name: 'x',
    description: '',
    source: 'user',
    path: '/tmp/x/SKILL.md',
    triggers: [],
    modelHint: null,
    effortHint: null,
    guardrails: { forbidden: [], confirmRequired: [], connectors: [] },
    lines: 3,
    contentHash: 'h',
    indexedAt: '2026-09-03T00:00:00.000Z',
    ...overrides
  }
}

describe('renderSkillsIndex', () => {
  it('renders the 架构规范 §4.3 table and flags high-risk skills', async () => {
    h.writeSkill(
      'workspace',
      'post-publisher',
      skillDoc({
        name: 'post-publisher',
        description: '发布内容到社媒',
        triggers: ['/publish'],
        confirm: ['发布到微博']
      })
    )
    h.writeSkill(
      'user',
      'news-digest',
      skillDoc({ name: 'news-digest', description: '每日资讯摘要', triggers: ['/news-digest'] })
    )
    await registry.refresh()

    const md = renderSkillsIndex(registry.list())
    const rows = md.split('\n').filter((line) => line.startsWith('| ') && !line.includes('---'))

    expect(rows[0]).toBe('| Skill 名 | 一句话用途 | 触发词 | 来源 | 是否含高风险动作 |')
    expect(rows[1]).toBe('| news-digest | 每日资讯摘要 | /news-digest | user | 否 |')
    expect(rows[2]).toBe('| post-publisher | 发布内容到社媒 | /publish | workspace | 是（1 项需确认） |')
  })

  it('escapes pipes so a description cannot break the table', () => {
    const md = renderSkillsIndex([stubSkill({ description: 'a | b' })])
    expect(md).toContain(String.raw`a \| b`)
  })

  it('collapses newlines in a description onto one row', () => {
    const md = renderSkillsIndex([stubSkill({ description: 'line one\nline two' })])
    expect(md).toContain('line one line two')
  })

  it('joins multiple triggers with a line break', () => {
    const md = renderSkillsIndex([stubSkill({ triggers: ['/a', '/b'] })])
    expect(md).toContain('/a<br>/b')
  })

  it('renders a placeholder row when nothing is indexed', () => {
    expect(renderSkillsIndex([])).toContain('尚未索引到任何 Skill')
  })

  it('marks the file as generated so nobody hand-edits it', () => {
    expect(renderSkillsIndex([])).toContain('generated by arms-os skill registry')
  })
})

describe('writeSkillsIndex', () => {
  it('writes the file, creating parent directories', async () => {
    h.writeSkill('workspace', 'a', skillDoc({ name: 'a' }))
    await registry.refresh()

    const dest = path.join(h.dir, 'nested', 'SKILLS_INDEX.md')
    await writeSkillsIndex(dest, registry.list())
    expect(readFileSync(dest, 'utf8')).toContain('| a |')
  })
})
