import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { MemoryAreaSummary, MemoryEntry } from '@shared/types'
import type { MemoryStore } from './store'

/**
 * Router file generation (架构规范 §5.1, 系统设计文档 §4).
 *
 * These files are the user's own documents, so the writer never owns a whole
 * file. It owns the span between two markers and nothing else: text above or
 * below is copied through byte for byte, and a file that has no markers gets
 * the block appended rather than replaced. That is what makes it safe to point
 * this at a hand-written `CLAUDE.md`.
 */

export const BEGIN = '<!-- arms:begin generated-routes -->'
export const END = '<!-- arms:end generated-routes -->'

/** Files per domain index. Beyond this the list stops being a useful pointer. */
const MAX_AREA_ENTRIES = 200

export interface RouterPlan {
  file: string
  /** Full contents the file would have. */
  contents: string
  /** False when the file already says exactly this. */
  changed: boolean
  /** True when the block is being added to a file that had no markers. */
  appended: boolean
}

export interface WriteRouterOptions {
  store: MemoryStore
  /** Directory the router files live in - the memory root, not the code repo. */
  routerRoot: string
  /** Produce the plan without touching disk. */
  dryRun?: boolean
}

function block(body: string): string {
  return [
    BEGIN,
    '<!-- Regenerated by the ARMS Memory Indexer. Edits inside this block are lost;',
    '     anything outside it is never touched. -->',
    '',
    body.trimEnd(),
    '',
    END
  ].join('\n')
}

/**
 * Splice the block into existing content.
 *
 * Three cases, in order of how much they respect what is already there:
 * replace between existing markers, append to a file that has none, or create
 * the file from a minimal template.
 */
export function spliceBlock(existing: string | null, body: string, template: string): {
  contents: string
  appended: boolean
} {
  const generated = block(body)

  if (existing === null) {
    return { contents: `${template.trimEnd()}\n\n${generated}\n`, appended: false }
  }

  const start = existing.indexOf(BEGIN)
  const end = existing.indexOf(END)

  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start)
    const after = existing.slice(end + END.length)
    return { contents: `${before}${generated}${after}`, appended: false }
  }

  // A stray BEGIN with no END would otherwise swallow the rest of the file on
  // the next run, so treat a half-marked file as unmarked and append cleanly.
  return { contents: `${existing.trimEnd()}\n\n${generated}\n`, appended: true }
}

async function readIfExists(file: string): Promise<string | null> {
  try {
    return await fs.readFile(file, 'utf8')
  } catch {
    return null
  }
}

function areaFileName(area: string): string {
  const safe = area.replace(/[^\w一-鿿.-]+/g, '-').replace(/^-+|-+$/g, '')
  return `${(safe || 'root').toUpperCase()}.md`
}

function masterBody(areas: MemoryAreaSummary[], routerRoot: string): string {
  const rows = areas
    .filter((a) => a.area !== '')
    .map((a) => {
      const link = path.posix.join('areas', areaFileName(a.area))
      const when = a.lastModified ? a.lastModified.slice(0, 10) : '—'
      return `| ${a.area} | ${a.files} | ${when} | [${link}](${link}) |`
    })

  const loose = areas.find((a) => a.area === '')

  return [
    '## 工作领域索引',
    '',
    `知识库根：\`${routerRoot}\``,
    '',
    '| 领域 | 文件数 | 最近更新 | 领域索引 |',
    '|---|---|---|---|',
    ...(rows.length > 0 ? rows : ['| — | 0 | — | 尚未索引到任何领域 |']),
    ...(loose ? ['', `根目录下另有 ${loose.files} 个未归入领域的文件。`] : [])
  ].join('\n')
}

function areaBody(area: string, entries: MemoryEntry[], total: number): string {
  const lines = entries.map((entry) => {
    const href = entry.relPath.split(path.sep).join('/')
    const label = entry.title && entry.title !== entry.name ? `${entry.title} — ` : ''
    return `- ${label}[${href}](${encodeURI(href)})`
  })

  return [
    `## ${area || '根目录'}`,
    '',
    `${total} 个文件，按最近修改排序${total > entries.length ? `（只列出前 ${entries.length} 个）` : ''}。`,
    '',
    ...(lines.length > 0 ? lines : ['- （空）'])
  ].join('\n')
}

/**
 * Build the master router plus one file per area.
 *
 * 架构规范 §5.1's iron rule is that a stale pointer is worse than no pointer,
 * which is the whole reason this is generated from the index rather than
 * maintained by hand.
 */
export async function planRouterFiles(opts: WriteRouterOptions): Promise<RouterPlan[]> {
  const { store, routerRoot } = opts
  const areas = store.areas()
  const plans: RouterPlan[] = []

  const masterFile = path.join(routerRoot, 'CLAUDE.md')
  const masterExisting = await readIfExists(masterFile)
  const master = spliceBlock(
    masterExisting,
    masterBody(areas, routerRoot),
    ['# 知识库主路由', '', '这是 ARMS Memory Indexer 维护的入口文件。'].join('\n')
  )
  plans.push({
    file: masterFile,
    contents: master.contents,
    changed: master.contents !== masterExisting,
    appended: master.appended
  })

  for (const area of areas) {
    if (area.area === '') continue
    const file = path.join(routerRoot, 'areas', areaFileName(area.area))
    const existing = await readIfExists(file)
    const entries = store.listArea(area.area, MAX_AREA_ENTRIES)
    const spliced = spliceBlock(
      existing,
      areaBody(area.area, entries, area.files),
      `# ${area.area}`
    )
    plans.push({
      file,
      contents: spliced.contents,
      changed: spliced.contents !== existing,
      appended: spliced.appended
    })
  }

  return plans
}

/** Apply a plan. Writes are atomic, and unchanged files are left alone. */
export async function writeRouterFiles(opts: WriteRouterOptions): Promise<string[]> {
  const plans = await planRouterFiles(opts)
  if (opts.dryRun) return plans.filter((p) => p.changed).map((p) => p.file)

  const written: string[] = []
  for (const plan of plans) {
    if (!plan.changed) continue
    await fs.mkdir(path.dirname(plan.file), { recursive: true })
    const tmp = `${plan.file}.${process.pid}.tmp`
    await fs.writeFile(tmp, plan.contents, 'utf8')
    await fs.rename(tmp, plan.file)
    written.push(plan.file)
  }
  return written
}
