import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { SkillMeta } from '@shared/types'
import { hasHighRiskActions } from './guardrails'

const MARKER = '<!-- generated by arms-os skill registry; edits will be overwritten -->'

/** Pipes would break the markdown table; nothing else needs escaping here. */
function cell(value: string): string {
  return value.replace(/\|/g, String.raw`\|`).replace(/\r?\n/g, ' ').trim()
}

/**
 * Render the skill library index described in 架构规范 §4.3 - the table you
 * check before adding a skill, to catch trigger collisions and duplicated
 * purpose.
 */
export function renderSkillsIndex(skills: SkillMeta[], generatedAt = new Date()): string {
  const rows = [...skills].sort((a, b) => a.id.localeCompare(b.id)).map((skill) => {
    const triggers = skill.triggers.length ? skill.triggers.map(cell).join('<br>') : '—'
    const risky = hasHighRiskActions(skill.guardrails)
      ? `是（${skill.guardrails.confirmRequired.length} 项需确认）`
      : '否'
    return `| ${cell(skill.id)} | ${cell(skill.description) || '—'} | ${triggers} | ${skill.source} | ${risky} |`
  })

  return [
    '# SKILLS_INDEX',
    '',
    MARKER,
    `<!-- ${generatedAt.toISOString()} · ${skills.length} skills -->`,
    '',
    '| Skill 名 | 一句话用途 | 触发词 | 来源 | 是否含高风险动作 |',
    '|---|---|---|---|---|',
    ...(rows.length ? rows : ['| — | 尚未索引到任何 Skill | — | — | — |']),
    ''
  ].join('\n')
}

/** Atomic write, so a crash mid-write cannot leave a truncated index behind. */
export async function writeSkillsIndex(dest: string, skills: SkillMeta[]): Promise<void> {
  await fs.mkdir(path.dirname(dest), { recursive: true })
  const tmp = `${dest}.${process.pid}.tmp`
  await fs.writeFile(tmp, renderSkillsIndex(skills), 'utf8')
  await fs.rename(tmp, dest)
}
